config/routes.rb
Palmabase::Application.routes.draw do
  devise_for :users
  resources :palms

end

app/models/palm.rb
class Palm < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :full_name, presense: { message: "Please enter your full name." }
  validates :display_name, allow_blank: true, length: { in: 2..32, message: "Display name should be between 2 and 32 characters, please."}
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password_confimration, presense: true, if "!password.nil?"
  has_secure_password

  # has_many :plantations

  def admin?
    self.admin_status
  end

  # def current_plantation
  #   plantations.last
  # end

  # def past_plantations
  #   orders.sort_by { |plantation| plantation.created_at}.reverse
  # end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

app/controllers/palms_controller.rb
class PalmsController < ApplicationController
  before_action :set_palm, only: [:show, :edit, :update, :destroy]

  # GET /palms
  # GET /palms.json
  def index
    @palms = Palm.all
  end

  # GET /palms/1
  # GET /palms/1.json
  def show
  end

  # GET /palms/new
  def new
    @palm = Palm.new
  end

  # GET /palms/1/edit
  def edit
  end

  # POST /palms
  # POST /palms.json
  def create
    @palm = Palm.new(palm_params)

    respond_to do |format|
      if @palm.save
        format.html { redirect_to @palm, notice: 'Palm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @palm }
      else
        format.html { render action: 'new' }
        format.json { render json: @palm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palms/1
  # PATCH/PUT /palms/1.json
  def update
    respond_to do |format|
      if @palm.update(palm_params)
        format.html { redirect_to @palm, notice: 'Palm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @palm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palms/1
  # DELETE /palms/1.json
  def destroy
    @palm.destroy
    respond_to do |format|
      format.html { redirect_to palms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palm
      @palm = Palm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palm_params
      params.require(:palm).permit(:block, :number, :sph, :river, :road, :year_planted)
    end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  include UsersHelper

  def index
  end

  def show 
    @user = User.find(current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/palms_helper.rb
module PalmsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_params
    params.require(:user).permit(:full_name, :display_name, :email, :password, :password_confirmation)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Palmabase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/palms/_form.html.erb
<%= form_for(@palm) do |f| %>
  <% if @palm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@palm.errors.count, "error") %> prohibited this palm from being saved:</h2>

      <ul>
      <% @palm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :block %><br>
    <%= f.text_field :block %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :sph %><br>
    <%= f.number_field :sph %>
  </div>
  <div class="field">
    <%= f.label :river %><br>
    <%= f.check_box :river %>
  </div>
  <div class="field">
    <%= f.label :road %><br>
    <%= f.check_box :road %>
  </div>
  <div class="field">
    <%= f.label :year_planted %><br>
    <%= f.date_select :year_planted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/palms/edit.html.erb
<h1>Editing palm</h1>

<%= render 'form' %>

<%= link_to 'Show', @palm %> |
<%= link_to 'Back', palms_path %>

app/views/palms/index.html.erb
<h1>Listing palms</h1>

<table>
  <thead>
    <tr>
      <th>Block</th>
      <th>Number</th>
      <th>Sph</th>
      <th>River</th>
      <th>Road</th>
      <th>Year planted</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @palms.each do |palm| %>
      <tr>
        <td><%= palm.block %></td>
        <td><%= palm.number %></td>
        <td><%= palm.sph %></td>
        <td><%= palm.river %></td>
        <td><%= palm.road %></td>
        <td><%= palm.year_planted %></td>
        <td><%= link_to 'Show', palm %></td>
        <td><%= link_to 'Edit', edit_palm_path(palm) %></td>
        <td><%= link_to 'Destroy', palm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Palm', new_palm_path %>

app/views/palms/new.html.erb
<h1>New palm</h1>

<%= render 'form' %>

<%= link_to 'Back', palms_path %>

app/views/palms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Block:</strong>
  <%= @palm.block %>
</p>

<p>
  <strong>Number:</strong>
  <%= @palm.number %>
</p>

<p>
  <strong>Sph:</strong>
  <%= @palm.sph %>
</p>

<p>
  <strong>River:</strong>
  <%= @palm.river %>
</p>

<p>
  <strong>Road:</strong>
  <%= @palm.road %>
</p>

<p>
  <strong>Year planted:</strong>
  <%= @palm.year_planted %>
</p>

<%= link_to 'Edit', edit_palm_path(@palm) %> |
<%= link_to 'Back', palms_path %>

app/views/users/_form.html.haml
= form_for @user do |f|
  %ul
    - @user.errors.each do |error|
      %li= error
  %p
    Full Name:      #{f.text_field :full_name, :id => 'full_name'}
  %p
    Display Name:   #{f.text_area :display_name, :id => 'display_name'}
  %p
    Email:          #{f.email_field :email, :id => 'email'}
  %p
    Password:       #{f.password_field :password, :id => 'password'}
  %p
    Password Confirmation:    #{f.password_field :password_confirmation, :id => 'password_confirmation'}
  = f.submit "Save Your Account", :id => 'save'

app/views/users/edit.html.haml
%p.flash= flash.notice
%h1 Edit Your Account
= render partial: "form"

app/views/users/new.html.haml
%p.flash= flash.notice
%h1 Create a New Account
= render partial: "form"

app/views/users/show.html.haml
%h3
  Full name: #{@user.full_name}
%p
  Display name: #{@user.display_name}
%p
  Email: #{@user.email}
%p= link_to "Edit", edit_user_path(@user)
%p= link_to "Remove your account", user_path(@user), method: :delete, data: {confirm:"Really DELETE your account?"}
%p= link_to "<< Back to Menu", items_path